
spring.data.mongodb.uri:mongodb+srv://gerhardgaube:test12345@testgerhard.0rechap.mongodb.net/?appName=testgerhard
spring.data.mongodb.database: swd24



server.port: 5000
service-name: lab2-rest-mongodbatlas